#!/bin/sh


mkdir -p /srv/rsyslog

if [ ! -f /srv/rsyslog/rsyslog.conf ]; then
  cp -p /etc/rsyslog.conf /srv/rsyslog
fi

rm /etc/rsyslog.conf
ln -s /srv/rsyslog/rsyslog.conf /etc/rsyslog.conf

if dc_is_unlocked; then
if [ ! -z $RSYSLOG_TARGET ]; then

cat >> /etc/rsyslog.conf <<'endmsg'
*.* action(
        type="omfwd"
endmsg
echo "        target=\"$RSYSLOG_TARGET\"" >> /etc/rsyslog.conf
cat >> /etc/rsyslog.conf <<'endmsg'
        port="514"
        protocol="tcp"
        queue.filename="fwdRule1"  # unique name prefix for spool files
        queue.type="LinkedList"
        queue.maxDiskSpace="256m"
        queue.saveOnShutdown="on"
        action.resumeRetryCount="-1"
        action.resumeInterval="30"
)
mail.*		/var/log/maillog

endmsg
fi
fi
